
# development script

version: "3"

services:
  mongo:
    container_name: synapsica-db
    restart: unless-stopped
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo_data:/data/db

  server:
    container_name: synapsica-server
    restart: unless-stopped
    image: arpitgo4/alpine-node
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    command: sh -c "npm install && npm run start:development"
    expose:
      - 8080
    depends_on:
      - mongo
      - api_gateway
    environment:
      - MONGO_HOST=mongo:27017
      - MONGO_DB_NAME=synapsica-game
      - SERVER_PORT=8080
      - NODE_ENV=development
      - JWT_SECRET=U5ZnTwt0tpmUHAVhES51iXM52mFSbxsOojFs5JNnZUv082ZACjnsuRNklomA
      - JWT_HEADER=x-token
      - API_GATEWAY=api_gateway


  client:
    container_name: synapsica-client
    restart: unless-stopped
    image: arpitgo4/alpine-node
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    command: sh -c "npm install && npm run start:development"
    expose:
      - 3000
    depends_on:
      - server
      - api_gateway
    environment:
      - API_GATEWAY=api_gateway:80
      - NODE_ENV=development
      - PORT=3000


  api_gateway:
    container_name: synapsica-api-gateway
    restart: unless-stopped
    build: ./api-gateway
    ports:
      - 80:80